In [1]:
import os
import pandas as pd

In [2]:
top = '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder'

In [7]:
data_record = {'path':[], 'slide_name':[],'label':[]}
for root, directories, files in os.walk(top, topdown=False):
    for name in files:
        print(root)
        print(name)
        data_record['slide_name'].append(name)
        data_record['path'].append(os.path.join(root, name))
        data_record['label'].append(root.split('/')[-1])
#     for name in directories:
#         print((os.path.join(root, name)).split('/')[-1])
#         data_record['label'].append((os.path.join(root, name)).split('/')[-1]

/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GGYHFAVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ECPVWKSG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VDCVCPSP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PEPNIHAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IANDFGMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GCEIRVHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YSSSWGGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RQHKCEFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DWICCYVY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FRELQPGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QDLYQASD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CHEGSMLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FWIWKWMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VEAADKHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NGGYPIFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MGQHQFNK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VLQMTLQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CHCGYHEC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MEFRLSHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GSVVIWCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SNNLPQWY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AQSIRAMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DNQPHWHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YKRLPGCR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CHNWNPWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FYWNDIHQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DNMMSPGN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YTRACRSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YKLKSQHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CIQWHLST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YCEMFQTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NPCKFEER.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CPLSWKIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LLYCHPVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QTNSMWVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GINLHEPA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MNNTAFAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AKMNGAKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EIWHQCVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HNNNNYPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RQLKCGWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YFPLWFTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WLSHFPYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QFPLQPCE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FNMNYVPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YPQQQDWD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HWTFRTRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TYSGQGWY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WNHVFLNP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WCPYTEGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PLIFNRKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ALMCLIKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HDDCTQYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TPICCYRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ESRYWMKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YNGWAISL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VKPPKPFS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CDGDANYN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WQKMTTIP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LLGMTHKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PEQVTVCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PWVNPNCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RTCFCLWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LTYYPSMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CLPKLHLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LHVYHTLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DNFYYHPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RCDCGFHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NPVIPHTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GWVSPLFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KGPEQHNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YQHNACRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ACCASYIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WQCYWSCD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LCHIQYSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EWMRSSWE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VCGYHISF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GHSVVRNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SCLQLKRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YDNEFKSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KMDVMIKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AKIEAEVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LDDGQWLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PTPTEDAD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DFMDTDVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MWIGWIPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EWSFSEYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NTNKRRNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DAWHWIRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DYKIVIYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NWGEIYNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RNICMKCD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NMVWYITN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TVQYMKPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WMKPKIYN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EDDCPLCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SRPEVCCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FPWCCPSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HIERARWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PQKNGCKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HTSDRSAF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DKSHTVEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HHPCECSS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HMPRLAMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EAYHQNST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AEQVDEGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SEQQFIGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AYVGMQYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NCYNGTMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SPYHQVND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CWIQRCSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KCDSNDIE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GESSEVET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FKRCPLAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VMFRCYMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WSKSHTET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RIVPLYQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YYLFADEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EMEKKPMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AYFEWGEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TRCDTLIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NMQMTFFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MILDQLMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TALAQSVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IVWYGHPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GDHGGERG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MLESTKGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ACAMSPSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YCNEWPSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MAPMDTPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YILKSMQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NKHMMDVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SKTVSHSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WVRVQWCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LLIVHHGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-INSGVMMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GQKRIRVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CVEAQQTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PLNYAQDS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ELDLGDLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IHEKRVKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ISFCTSCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LNDTYHDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QCYVNRFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EEGMPKMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CCHSIERL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FQNFLNQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RWLDRSCF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PGRGMDCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CCRARNWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ERWSHSQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KHITPKCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FSYIVKGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WCAAWAHQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YHPIRMDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HSWNVKYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FREWFTGS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MALDYAGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VPGTYHCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RTGLVYDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QCCYYVKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QQWVDNQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KFNHKDIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QSYDICSC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QRKVIASD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QQRWKGEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VDLCLMYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PDLFTQEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FYADRYHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NQAAEEEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RIDIFEWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KNNYNDWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RPDVDVHH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FPTIGGCI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PNDSYFMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SYNCPGYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TNNRQQQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YQVMGWWD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QKPKSFYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YGEMKKGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MKRMREIR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TPYMDVLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EIAKHQAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KGTQCVYF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VMYMQRDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VWQCAPWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DMWSNTHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MTRWNHDY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FWDVPAFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GTNFRHAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TFSVPLTK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GHKTMYGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CIMFYFFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IIHCMHRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CCGHSKGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HWPTQFHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RMKWYLVG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TDKHVAMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TKVAIRRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TRFYIYLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KKQWVMGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GRCHLNDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QELNRQFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-STHHVNVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LPVCMNLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MTPSGTMY.tif

NORM-FPPWEHLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AHEWNQTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YIFCVYGW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LPEMVVAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DPRLICMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MLGETTMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DKDRNSIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DIYVPHWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PHCMSILY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KFKEGLKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DFIICSKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IWKYRGKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WGEFEHEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PDNVHVYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GYGIDMIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WGWGGGWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RQRIMCQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VTNHVWND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HLQIWNVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HGFTQYGW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FAGIYICH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EYLMGCRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FWGVWQNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HTWCHYFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SSVIEWMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PYVHVHQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LIHKADNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PGEWSTFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WFYYGDCR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SYHAKIMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KHWNTVRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SQIHARAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EWYLMQQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KKDITMPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NVIWDFQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FPFGFVYF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DYEQCGTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MMLPHQYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FAPIACKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YLQEPSPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SFFIELSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RVLWLQYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YMYHGPSH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GANTLHDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GTDHFCFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IVCWPTWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MNNAKCIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ENLISSSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DDDRIYSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KVEHVDHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ATFVLALR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PACVDGLK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YEEEYVTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ANRGCYEH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RYEICPHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CGVLHTNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NFRVDHKA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KQEQPRKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GKTMYCGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KDGDGQNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ANRPDMPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SGCYRSCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VHVSVIFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SILPYQFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FKSYCGVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DHKFRLPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EHDDPCVY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DNGSDGVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IWENGEEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EFKQFKCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TAGMIRDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DQGKDQPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MRICYHEP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QGHIVAEC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SNGKRACG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PFNQHEHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GFVECFDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GTTEPRMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TFDTIPHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FEPWDACN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RQLNFCFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ANHCARTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GIMGHYKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VHGLHQPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FCLGVPGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LDQRCCAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MMHGDNFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TMCPTGVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PFVEQKIE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EKKGLPPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HTTLVPHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CRTDRWDY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VVHFIMPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PRAFPPWV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RNAGMYTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ELNGTHNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AEANPTAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HGRAFSRV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SPAHEDHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ILNWYEPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AEVKGENY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SDSRDEYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CCHQFRYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PPVAFPRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AHHCSTAE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IGYRIEGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CHGCMTKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PSYREQYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KTYMNFPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DYMYTQSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WWDAGGWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LPARCWKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SEGDPSAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HLCETYMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EMAYVWKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VRWRWSSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AGDAQQQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YFRMSEGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YAGWKSKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LYFQFTPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GQYIWDIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DIMALKPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QAFAWVDC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FVVGSHPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VCQDIVWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LSEMDPED.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FHDPFEYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QCFNMTPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SLAMKTVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CHRWVMNL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VYKYKHYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KMVHIWKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DWGVIEQA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SHCTPHWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IWCVDRQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DLITLDQW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QIVLWFHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CQRWYQCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GRPRNDQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GISAFNYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EFIWSWWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YWLLPSMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HGMWQWFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PKAGQGDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YKVARMNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YSWMQVYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IGAATSFS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FPTWESIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IGNFPNCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CNVAWFSI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HLPYSPYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RIANSNLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FRRERHQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QLDNSHTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GFDWHCAD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WADWFQEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PKWAAMHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SWPWSEDG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KHEAEWQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WEWTLNFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EVGTLPLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KFFFVTRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CKQRFYWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HWARHRQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SQYKDGSF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IKRQICTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YTDNIYST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PWADRDCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DTDVLNQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EILFGSRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ISRPGFCY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AIDPQTHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EYHMWVCD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FDRQMDAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WAWVEAFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MIRHYRGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SEDLGCSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GMMKICVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SHNRFEWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ACTHEQTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TKVCQEKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MAPKHRQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GWYRWTNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DVSNPVGR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FAWQKTLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YGITGNQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PPCYRRTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GKSVVWQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HCIKYTML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VETYRMRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FQMRPEPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FSHYTICM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IFSEQVPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GWPVAVLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MFYDCWVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TSVDQCCY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PDIHFHCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CTPGCPHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IINLGYYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ASSAAFTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LHPETMCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ATEWETTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FCIWMICE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AKGRQSTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DAHHRHGS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LSCNYLYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WKQFARMG.tif

NORM-RGGGKECT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-INAEHNCR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QFRDTIDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KTEMETMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VECLHIMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YGGFCMGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EFRGAWEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QFIDMRES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CVGHYKED.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QWRLMIRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QEPFNITV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WPDVSFMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DNMYETQA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NPAWIWTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KWREDIKD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FGDMILDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YKCFVNMS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TKQHNDIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YLITTRVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TKNADLWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WLWIINPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DCRTPEGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EVGTSKNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IMLTIIKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MEVHTGQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-REEQKAPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DLPLWTCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PKNNPCRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-THPHVAAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SLTCEDET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VARFIGIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DWHWLLLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NPSGSDCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QMLCECHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TNYIRPIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SEVLIAMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CYLVTQWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IEMVPSVG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RNFHPWGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LSEYCGRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WQVAWRSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SICKNIEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DINIWLWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RTMSLTLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GVMDFSIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YRCMGTWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FRNCCKNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YISRPFEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GTVHQYTV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YLGSLVDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RWGWNKMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MSCHPEFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MEAEMVHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IPYPRWQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DYNRRFVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SIPPPHWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MYEGYSMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SWTKSNDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DHVYSCRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VTRSWTKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RLKPRWFS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TNHEDCHT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QRFFQCIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HTVVYSAG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RWFECERD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ALQLCQPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NNITHHDM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WMWTLQGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TVMSNRNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YHCIEMPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MPNSERGS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FGREAIWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NITVREEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SEEIMNET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KNPKQYYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EKDGAWPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QSYDEVEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PLEIMPYW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FFDTWFGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AFEEGEQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SGRQPSTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GLMQKFGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RNGWQFAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PCTALKAF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PRFGHRLF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RFDPQCEH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HHSDGNRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TVCMPYKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VEYYGHNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KNGFIWQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RWRYHIIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GDRMLQRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FMIPETMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GVSLWFNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WLVETISY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NWRNLMVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QEYQGYKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TMRNMWQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ESIKATMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KNLCFAMS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FHMPWSDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RWNMFRGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ITQYLFRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RMQFMWTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NCDIEIRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KFAPTCKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MREALNNP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MKVDDHPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HPAWMKWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SRLKNDCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HIATYYRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FFHTWHMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EGVDNRDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GSFTRMCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MTTHRLIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GNPVCEIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TKETQQAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LSKKYPPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MVGNFCYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TQNIFNPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HQVQFREY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TYIQYADH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NGYGVVST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GEDHGKMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YHMGPPNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FISTDWAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WCAPGQLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HYPCHDAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DEPFPKKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FVVVHCDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FPDACLRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IKEDIQTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HKNTPFEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LLAEPGTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MHWCNKMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GASIGHYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RKGWVESQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RFGPRVMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MIKKAYVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IYKHNQTK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HLYYCEMQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ICCSNCWV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QEVAFWFR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CKCDASTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QKARDPNC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YYQDPFAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PQIIMEGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FHKHAELM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WLGIHYNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CLNVTWCE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IKSHREGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QWATMPFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AIHRWKLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FCPHVEGW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DKHYVICM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-APTDENAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CEGDQCHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VKKCCQCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PHLFCFFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EIANACWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AVAADPKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NCYFRPAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EIKNRWGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YFMVNKMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AHRQRIYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GENAWFPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DFTNYTGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ESCEYMLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PATRLCQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CICHADKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VHANLMLA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KTTDDLKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FEAARRDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ILWLPSDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RGYAQQLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QAQKVCHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YTKPTHMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FKRKYYFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HYCGWDYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WPMLSVPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PWYDKDIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MVCDIEFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CNHSGCHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ACTPQQMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FKPNEMHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PPWAIGDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QVWPTWWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VNVCQAKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GYAQYVPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YSGASERF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TKELALMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EPPQRVSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IAEHFYTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DHYYLDQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IILKWNKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IRYKLCGI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KWPCDNVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PHRAWQAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SMGEYIGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RQDHQRFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VYKQWCVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LLHNMPWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CEGGAQRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YKRRPQTK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DVQGPQHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MMPHVPQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RNAEPGHM.tif

/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RPLRHMPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MWIEINQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NYKGYVQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TEDRNACH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FMSMWVGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FFEEICQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CCVYGMFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AFECIWTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HADIDNWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LYPQKLSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LFVQSYYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KKDTVETC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AKCANHMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QINNKHLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WWQDYWAF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HSGKWHHT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AGWNFGLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HIEHWKMV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VTPLGSGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CPVTEQIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GNRAGSIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MSGLCPQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FHREDNDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YMWPIQWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HKIDADDM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VRPEMDWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SDIQERMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CTMMKFHQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VHRQYINF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WGDNFEVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YIEGSHFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EWGVWHPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CRNWTVAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LKITSSST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VQWPCITG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PLEYRWAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LIRMVIVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YNWPKTVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CQHVSVGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MNEYAWNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PDWVQETN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MDSWSFGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VAADILFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TGINVSMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TFYSNVPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WRKHNCRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RKGWDPKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HAIQCYTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GICKACSI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TQAECSIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MQSTTECF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IRAKMWMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TQMDTHWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SFMQHRFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FVPTDPAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MLWCIRKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SAYKAIRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FPQRLHGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RYPSMRID.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DIECTGSG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KILLTFEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RIHEFMIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ERMSTIWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VHMMRCSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VSHRSYSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GILCAAQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NLHPFTVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GSYQEWQH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MSVGCYFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QWTILECR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GLDTTPMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EIGPECHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ICDFWFER.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KAYTVIQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VNCCKGLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LFQLCLTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KEFTVYRQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CSDMSEHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SDHNSDMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AFYQAFMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ACEQVKWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KPHENGHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KYFDMVEW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DSIHPDPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RSKIMNMV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ERDDMMWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NPWHTFNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PSRGYKIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GCQYNYEC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WSDNFMLR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VPARQGKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NPGFITFR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GMLMSKTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CWEYQSRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CGQWPMGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NPSNSFNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VNSQYQLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RTTFYPQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RANVNQIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CQWMWSPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LDMQEDIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CGMSVYFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CGCILRGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SWLSSNEP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NHAATASH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DYYDYKHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EGVFYLYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IDKQSNHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YAKMPMNM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QIKLKDII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TDAILIHQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TNMEGPFS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CFGRKWHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VSQATSKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CAFVHVHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WHKIMPEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WINPIRKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SAAQSDPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FAWRLLDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QERSQKIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SVHKGSDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VKAWIHSW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KGMHSQNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LIQMYHQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KIRMWSVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VQIRRSPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WMWKEPLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KCSGSKLA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YWNWFGVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CWDDHKTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WDEGHSVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WHCYDQFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-VNGSTKMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FWCTAWCD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-MLERLCWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ISCPLKRK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SYKNTPPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CWWCKMMS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GPQDVVRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IDVEMFAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SAHYSSIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TTGMNGLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WSCRGPLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NQHNDDPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SRIEQRLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FFIYKFSN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AFWAKGSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CKPQRCLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LTDDGNVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TSGWDIIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NPRSVFQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QWSPSATL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GHSFKDLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IYYYKTIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FRRQKPVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IPTNKAVH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RQKPYTCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-IQDHCDRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NICQGHYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NEEEKWDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ISLFTRKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-EMLQEFMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TTFCIKHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WRTCNRCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SPMPRMHH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GIWEGLME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CQFGELQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RCVLYVVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ALMKYDHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TFDCMCAG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RMECQYEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AKWPQRCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AAQPPHFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HWEKAEKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TQWGCEMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YLYNRWTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FYTGGIRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WYSCFCFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PMHPCFGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-TQNESVCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SLWPNYML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-CTLWTKAM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PYVKALKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-HLWDKNPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-LLQLCTTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GDCNQPAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-RNAMYSMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GVMCDQPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WIREQLTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NAAMPKWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WDRYCPTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-AQIIMETN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-ISYGFHTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-NWQKFSFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-SSMPFKEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WLGGWNKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-INCQMRPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-DEKSIQYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-GDMKRLHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-YPKFIVAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-FMISAESV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KSPCCMVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-QIMQMCKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-WCGQVLHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-PCCSCLFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign
NORM-KQWITPFN.tif

/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TDKSQFQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WWGDQKMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SYLWGVTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PISAQLRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GEDTNWLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VCYVRFDH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QLYHHKCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ANSRHIRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VICRTTMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YHFFDFYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DASASCIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KTWAQCQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RNYKEMHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AQARDEGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CSSWLEWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PTVWNPTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KDPPAPEP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KVDQGADG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DPIAYLEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CYNGIHVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AHGGCGNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AVWVDGCN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NRKQIPWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AHRWIQTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DWYMVLKW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KACNAMTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TTQAVHDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GKISKQCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LLSMWKQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SGMQWKDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SFTELSIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LIHWVYWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LNVQWDPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KLWNELKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PTRYATLM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AYMPSRQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KIWKYTHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FPCYGNEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LMMVRTDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TWQRPADP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DGRDNLYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IDYWKPNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AGTIADPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RLDRYKRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TPMTHLGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GHRNLSQA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MQRFDDPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AYHKHVNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QSYHDVQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AIGPLTPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LRSQSQTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NLQNHWLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VENTMNHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FWAAHNFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LSNEQATQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TPQKKPIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KWCHDREF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IYTRVTKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GSHFDNRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YIKIYIKA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LLSRNWFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FPSVHALW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KCQIPGYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RDMSICLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ECQEVKRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WPKDSHMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FEFGSENN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SEWHHNNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RRWGAYVH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SCQEKDVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-STFVEPCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TDKGSYCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YVPNPYCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MPGTYWIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AAPAPIHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DEGMQVGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TSKTYSSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NFGRAMFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WNCHHVGS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ILHWDINC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EVIESVRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VHFTMEWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QADPNWRD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KYIKTGPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YGLEVIRW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MRDCKWQH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HIQDGEDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DTHILPHT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YDYNWDST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HSTMRLCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FAASYPHH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SQYTTQVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DWWENRGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MPIDTFNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YYWMVQIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SEHTQFIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RMKMKWNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GTIKSSKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-THRYVTKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NRLEIYEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GNNDTVYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TMQMAKLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HIDWRYVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HLCFNCIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AGQVPFPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ANENHTTI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SGIVQGPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WHTRSTEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YIAGFGCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QLVWRATV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DKSYVWKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EWVHRWRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YRAEYAPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YIQYCTMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NLSANFME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QVLYRAVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ENFCMANG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ARETSTLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YYAPSIEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QIQRTKNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AFHRYVQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ILYPKYYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RMRYRLES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IEWRFSEC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LGMWRQLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VCWVCSCF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WGGERFKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DWYFSCMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IYRRSSTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HHHGATMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TGHCYGWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ILDIVDFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MKSVWSHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EMQVSMFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CTCFCLEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NVLNPPRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WHSMSHCN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AHPCNLNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PYHMYILV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VLSVANHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SHHWHHIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KMPQKYDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QLTCKKRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MHKSYIPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FGIPPLNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CYFVVKTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KENIYQKW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FWMQETSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NQQYYKCM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VAPPQHVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SCHDRVEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DYKEGNLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SYKHAPTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WIIRRTRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RCDPRVRC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ERITCCVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AFISQTVA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QEKNDTVG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RWLAGENG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PWMPMHPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VGWWEFRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PDDNYIVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WTTEMCNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HCYDNIVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MHGFVFSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LTFFRSTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QCTRQIFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DKDQTIFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PLMHQVPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DGTGPFYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VYSFSLKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NCCVRHFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PDVTSYTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KEQSHVTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MEDEGVGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MSQCRLVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NKWASKHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EGLKTYGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VAKCHTPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SADIGSIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SPPCVSVY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DARSRQSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LFFFFGFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NWMALNKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DFLYTREA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EVMDERRW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GFESHNPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LESNMHVE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-REWDDNDG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EDGPLNML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DDTDNQES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QSREQSPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RVCTNRVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QTREDFAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NLAAYAFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ERNHGWAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TPKCSPIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PANLDKPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MRFEQHGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YQRFFVCC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KLHQERTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NKVSEPRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VWDHSFNC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KVVWAQME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WWWMACWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VPKDCHTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DWKMDFCM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WMHQMHWH.tif

STR-MSTRHWEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CNTGRHFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HFMNGIHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LEVSMNYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CDLFDEMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MYLKWYHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ANWFLGLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QPFASHSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QWQIDASH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PHLLRVWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WYWDDTVA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QMYQLWRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NIDHDWGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NEDLVNEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VQWYTNQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VTQKIVNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VGQLPSAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AGERERYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CQQQGMWE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QFRDRDGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GNDDTYFY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RIQWPKDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VNESCWFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CREEHGQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YMVRWQIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SWWVFHIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YENGTFAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ISRGMHPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GKECVAYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YVFYPSMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MNEHGNLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TVSYPASD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FFNTDNQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PDEWHITK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GTGCYVPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CPWAFPLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CLTYRHNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KRMQYITD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SYEKQQRV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VTHDWFHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QTFIQSQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EPHIILAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ILAYIIGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RHVTWDAM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-STMNTEYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MEWITQLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TSKKDGEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NNGMQKAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VTKISFRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KNETSPKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ADGIVVPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AFERMKLA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NIIPAESV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WNSSFDLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PQHDRNFY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SIYGYFMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ILAQMRWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GQQYDSAE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YARQRDNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LAIRHYAM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MCWSVVTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KENPECSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HTSWVQMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ENHDKRWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KYGTDVQH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VTPWACYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WPQEEIGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IGPIPNPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YVVNPVIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HVTRVTVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CVWTCRWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TRWHDRWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KWGYDSYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CGEDYHAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IHQTFNRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ENAWTAAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TFYRFWFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IWIKMPWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RYGVPITP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IMVFHNHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EHKIIARL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VRAFDRVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HSVSNFVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FRTVPNQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AKYKWVPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WENVTSEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IEHDPANK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DPSAHAMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LQWLCHAM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YYTEQAII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CDHRLIKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FLNTYKYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MFSRIVHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NLPEMWDS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WVGPLRYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DNNWRPRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RGMWILGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WPNIFYQW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QENNICMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FTALPYYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ERELVLES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EPHTSGSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WLALLHGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KPKPILRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IRGALVTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QKDPTYRC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SSIWEVVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LHKSKHLA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MKSCSYCC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VSYYIIKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HKSSCRML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PWNCCKTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VAAPNHRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QLRIEWPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PPFKQCNP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IYYYYEYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ECLWPTTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GMYHSENI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DVVPAIVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FYPQGMMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FICQWEAI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SGKPHAQQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YFYHITNV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KQNHLKPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KHMVFLQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YFIKHEPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WSTGQVVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VLGQDVCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CESGRQRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YARWGRVG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TRGMVMYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MVTACTVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DADVHKPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EKFSTMKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TNHPTGYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RHIMKHMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LPFPQRMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QAVGTLTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VFNQAFTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QTFIYFFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NNRGLEPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QYELNYCI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VYRIRFPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WHFEMLYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KYHQWQIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IRTRKFPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FWFITGLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CYTAFEIE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TTGHVYQY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DEEGEAQW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WVKWIRCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IVIFWVNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MTQHNPVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SFMTCQFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EKNPDGWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DITIKEHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KPRKDEWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GKPENQAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PCCVYFKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DMKPYMYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EKTEHDNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MKRMCFQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AYYGHPSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NCIQFADC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GQYSNINC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EEGATGHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VSTQIIEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WMHQPPLR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KINCEMLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KNVVVLIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IKWQCTRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GYKKKCIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VGRDSASE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HLDIEGLR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GTGQFAWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-INCPQDPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DASTEYKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HMHWSWFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GFQYYMHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FFQAKKVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GIMVIERE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LLTWRGEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NVIMYTTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YSKDMMTP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IHRPNEMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MHKNRSFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TGTTGQIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MHRYVMAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CVESKDQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RLTIMILW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GVWSFADQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IWPMAFAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SMEAMTFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YHQFSPLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PSIRCNLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HGPELQKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VQNYKFFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DFFRPFWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VMPHRELV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MVMCCINV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TEKDQASS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AMKSRFVH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FWGRFANR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HNIIHSSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LWPFCWSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CASKAKIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RKRDSKNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YDFACSLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IFIATRHF.tif

STR-WPMFYRKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PMRRTGHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DNRSPTNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ATTIDFKD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ACSCYVYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CMMRPRPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KWQERRKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LFIIHVYF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DMASESFY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MIPDFTIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MENCPDAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FFRRLGVH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FYRPVPQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NHSTHSLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CDFTGCLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EAKPVRSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QMSWYQTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PWHPYFEH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NHYAVFFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KWQLIYWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IFHADISN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FGVHHNYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NNGDPKQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HTGEAWQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NHYHQSDC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SKGGLWTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QYLTRKLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NECAICSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VKKMVHGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KLQNVEMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LALKGVPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NIKMHHYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VKCFPNAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RYSDKRGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MHDHYDPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HIMYKRNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CLFHDPIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YGGATTTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YSHMTWND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HEDQFAFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PLNNCFAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LFHILDLH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DHPPLFPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NTRWERPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ASQQRPYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SMTGLEES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TQSNTWKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FTVDQPDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GGRRWCIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MPSTWRDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FDSACYIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YHIINNTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QTHIMPGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WHVWACSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SFDPMISL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RVHDQYMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QYELPTQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ALDTYNNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TEMGDCVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EFYHNPKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-INIPCIFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DCTHPYEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VCCRAPCC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CGIGENFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YNVAHNDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VAQLWTWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LRWGIMDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HSPKIATD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IPRMRSMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QRAGCDWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LINAKKPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CVSWWGDT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MACVFWFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WINTPCNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DYSLGVCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KQWDPKNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HQQMKFWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EHEYYIMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AFSERVGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TQNCTPEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DHTGGWRC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PVHKYGLK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YWRWSDMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ADNQRNIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LAAVSIIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IMEPCKPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IIPKHHLK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MHMSMFAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DIDRIQVG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DLQTDGIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WQCRDKDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GEWAHDCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IYWSATCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WECEDCWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CVYKSKEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DHDYMAQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YMLRAHAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DLCMYMPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NFIQAQRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LPFGCKGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AEPGYCSC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WFEVHCSW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NNEQMPMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WTPHQYMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GNLLFIKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RLWWTAND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-INYHDPLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HAQFPAFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LPTKFNQD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RQNGSRAH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ISPPRQRD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EGSFMPLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LDMMWRWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EDTWMTIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MARMSHRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FQFLGNFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EADVMMFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YGTSVQLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PSCSHWPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MRNMPDGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YQPRTYKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SFLFELES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HEALIFKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TCYTDGKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NWRGHQHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DPVEVGFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SVQSTCWD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NIHSCPKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WKARPSQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HWYVPPRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LKSMQRWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WYMIKPHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LIVLMCMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VSTIDQPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MHWESPDH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RDIETKHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-SCIFQNQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KAFINRTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TTVPTFSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WWEYRFCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HSVKQGIR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PASWWRYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FTHRFNWE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PKWWGWTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VQRCTVVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GHQYMHAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ELRGVHIQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WWPWWVDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ETSLLMAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-IKANNHYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RKDCVDEW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VNGTTSTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NCICSEGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QTRGGHPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PCYYDDEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DSIKIYMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KVVWEWLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DTWMTLDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VRMWFCAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YGHPHPYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EAPWAEGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PINAYMPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ISQASYVG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MQQDFCKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FMAAKKRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HMIMDYEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DMFMSPMQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LAITVMFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EQGELIVE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FDGRNEHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-VRVNVYTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-AYFANQMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MYRLWVTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NYISLMCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ISKWESNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CYALMVRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QRPNYERT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-RWDWVSQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LAAYFRCN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-GIRRHGRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MNYNPLAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EQRGGVVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DNCSRMSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MRPAVNVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WNGMKDFY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TYSYEYQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-WDKGNLYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CRPTAGVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TEIVYFKW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FMQYNMPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-YAKQPYRK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CFGNGKPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-TRILCSAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KYVIRENR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-QQLSFSDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-PLKFCQNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-ENKHQVFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-NWRMSPDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HWGPNLPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-FVTRLSGI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-CDSETNEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-MTQFHWTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DIILWNHQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-KRPPQTEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LIFFFMGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-EPQHDMFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-LCEDWQPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-DSNHAHIQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Stroma
STR-HLDKASRP.tif

/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GMLSDIAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CDWKMKGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VYYQQYEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NRCIHMTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MPVGTCLA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GQRTSWWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YGSLFCEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MWYVQWVY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SLLYHCKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FNVPHYHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EINNWVHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YLIRLEMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AGSYTDLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WFMCWSNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NERVCTMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QIACEPMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GWNTIHRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RRMVTCWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TDYSWYVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ENARTDSG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YPRLIKLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KGFLAYWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WDNNWVVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KVHGWYGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VHRMNFSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AHRFCMKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YCAFCRYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KINNDSPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EFRAFNAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HNRFVCHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PLADDCNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PGGNVESK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PNWEDHKA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FFVVEKND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YGSQESRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LASVVLGR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RFFSFHTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TTIETWVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NPTCYSFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MFESPNYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ELDPPMST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LRAPADEP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RGLKYSSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LHQLDYHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GFAFYDPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LNAWDPDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NMLKMMMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ICGYYNGS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SKKCTIDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WYEDWWML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VRQWECRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SPGQFANE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DKPGVPHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RHTIPCEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NMNCTNEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SMYHWPAF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PNFFVDLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KAHELHWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DHNAGDTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IQRINKKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MKMETAEP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PVREVEKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CCYDSQEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LEGKHIQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WTSHSACY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YPKLADQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FMPYAHAG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EERGFYKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KRTDWGGR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KCTRHKAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YDAFFFEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TGKKHNEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DCDGRRDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DCQTFANH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SPMNDCGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IFKCDILM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VCDFQWTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VQTYLTDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FVNTEMAM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PEPCGSYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GFTYVTTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MSSIKPKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HQRIESGN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GALVVCMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VYYFSELS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ECFPFLHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TPHNYAQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LYGNSWTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KSMGPICV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RQKYFKPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ECERSTLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VDFKPSGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CFPRVYYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TCLEDETY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FLQDDWEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YYKTDMSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WCEQGTKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DWCHTCWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FEKPEPQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WCMPMWDC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PHKVRASN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LSRDLGIR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DPMNDPAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LWHEMLME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PLIPSPDM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PPSRGFPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RRTASEAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VMWSPAFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CLNVCLVE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GMRTYSLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ARHTYFWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RRNMFNRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FWTDNTNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VFKYLDWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IIWENYLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RTLKESQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SQNQGIVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HDPDMPKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PCLHCFWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MKYIILEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KHFLDGQQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VFIIGHKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PLMRVEIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EWPDFHTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ANPEDLPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ADVDRITG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HQYHGKVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NKLMWVHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CKTTSRAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FQTKSREW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IPIVRNVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NRLCICQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MKPFFLEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WALYWGQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FKTDPARS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PLRCIWVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DSHHMHRD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PEAHKLDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VCIVLLCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GFWKFFAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RQFAFVSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LQTLIVYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FGYQMMFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FLDDYSDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GIFRMPQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WQGISKGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HRKGKNSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-INWDPCRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LVMLFMCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EVWVQRCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HSFMETFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TGDGWMND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QVNRKYRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RWTQSVTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ASPFHAFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TEAIIHYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PWWKFCPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VTGHSLQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AMLDGGST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ENNKAGAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VRHGCFCD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SWQKHTYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HVTPGYLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FWPWGGWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IRKNESNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VEEVNMRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RWGFNYIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VRNEPSCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AVSKKRHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PSCCHRQH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ETSNKVNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HRERAVYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NPIIQKRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GGFNEHKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FCTHRFLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PRKEEQAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FEVSVPAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MVAQGFIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DGSWMCIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NEKWPPAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EYNIDRSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KSTAGYME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LIGFKHVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CQIKQMCF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MTEKKRSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FHVCTGWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KCGQNPWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LLHYMHLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EIQCICYN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CRVQYWPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GKDNKQWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EQVFNNFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WGWEYNGR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MWAARTPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WDWIEMNV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HKWNNTWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DPQGRMEP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CKTWHKVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IPWWNEHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DRWKAYAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IVQPEHAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MWDYFFDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LLSSEHET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FGYWEEIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DHWTLYYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DERIPNCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DIHFYLNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YFVDFYKW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GRTNSNVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YSTTHLQE.tif

/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ICNQLAKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KVNDLEKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RMYWPAPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CFPTEVHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HSPFMLYF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GFQLPPPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SQDDQHTI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CQAGWFPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-THYHDPND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CYGTTVLA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QCHMIDRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PNDITMKD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WNHYRQLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EKIFWCNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CDTTYSYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KQITPTLM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RCKTCHPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MRPQLIKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IRHGFAQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AIREFFIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GRKVQDVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FRWWNPGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DHCLDGEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MFLSTYRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VATEMAMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LGFDCDNK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NTPHVRWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EVFDEHVE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QFCDNASL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DLHAWASQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FDTSYYHQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DDTVRTEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KCEWKSPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CHNNMYDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FHHYVRWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SHLQQGFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LFDIQATW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MNRQTHFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ICNFATHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VVNWDYIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FRTPRPDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IPNGVSEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FQIITSRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SGMQHESQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TWEMGSSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LSDWQYEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TESASNCC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YIREGSEC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ASKVNLES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MHTFFVIQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PTWCMCWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KFAGRLQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TLRIMMMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MSIYTPYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DLPQTNGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TFVEAKND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AEKDYIAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NLNNNCCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YCFQDTHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RFCRSPNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VHRYDWWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MLHSVWCC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SHCFPTPL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EDPWWYLK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MAEIPCSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QHERLMFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IKTRWKPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PMPHTRFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TFIDCRHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WTHLLLST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SKPQTHEP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KWHMNRYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NMNLIAHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WSQHEGWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DRNVENLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EIAFKAWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WQKYTPYF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FPLPAQPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AEYFDPHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MFSPGAMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VTILPREA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ADWYWMKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KLCCYSEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-APCEITLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NPKQGAYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PGVDFFIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DQDLRIEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VSFQQALP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QQVDTYNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LAISGPNK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FTTPNFFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CFEFQLGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DLDLCFYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YYVPEAGR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WDQGSTAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EVQYKWMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SFKYTWCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PPGEFHFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CTRSYREQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CFGYTIPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YEWGKAIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FWDRARDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RDYNTKIP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FWGADGEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MSLQTYAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MLEKTSSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YDVLGDPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IPMCRVPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QWWRFNTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MFIWHPLK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NRSEESMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FNSDHRMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VVCYTWGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TLFTMYIR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QVKWALWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IPLSQLYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SNPVHDNP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-STCSLIKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CECSDATE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AYLYPLPA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RWFYLYHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TYYAFTSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HCFWQVWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RCYIKILG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TGILKDNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NHMHDMHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TVVPVALG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DLQQSILI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RFGLAMFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KQIKCKLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YQCSADEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SYASSAQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PSDGCNAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ETMTPHHH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ECLMMRHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EEPGNRVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GKCDAPKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VKMHMPTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CMVMNEFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QGHHGQPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CQQHYMEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RVHFFTEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WRDNADMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HAMSMDAD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VSGGTWCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VDWPSYCF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SSSAIAPL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-STVKEATK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VVRRMCHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QPTDNTPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AWLINPAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PMCSWPTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MNAPKTQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AIGWMWIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HWCKFRQD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MFHNPDLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WCTCPVEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PGLYTGMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KPESIPNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RLRPNQAE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TGDQDFWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HMPETVWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VWYYQMVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HSKQWQSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RKMKVACG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FFPAWFQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QATDWTAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LMQDMIYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KMSKWRWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FSAPPMAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LKSWFYFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WEMGDPRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NWVQGGYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DSIPEGVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PWWNGVCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-APYNWQLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RLFRIPNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KIEWETYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GVYEPEAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YHAGYPQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VTRGAWGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VLTNKMYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MYFIFNRD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YIFCGIFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CTRSFFWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DSHVIADS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QQRQFRAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HCPAWVYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IRTYPNYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PKPCQCED.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PLVWEVVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TNYYQFEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DRDEMDGN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AKENEWSI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IHLWMTTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LQPRDSHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VTKTFGCN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ANHGKECS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YGYTCYYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DVNLMHNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VLGLMMAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FDNTWYKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KTCMIMNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VVFQFRWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MMLVILME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TNMETLWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MYPRDNFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PAALRRTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AENTAAVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ELVYRLDV.tif

TUM-MLEWPDMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CWTYQNGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ESDNFHQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ASQGSMQY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DWLSYARS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YVQIWAEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CLCEDTEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PNSMKHVA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GHIIYTRK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TQSWRFTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SMQKARKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YNCKTKDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EEMNLRWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FCIGDTQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MVPHHDAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GEVECWDG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TGHKFDRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CFEWLMTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LSENDWWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FFQDWDKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KLSVWFEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NLTGPDNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RAVTVAIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CAELWIKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NKVNFDQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VYAIDSNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NWYSIRED.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NTNRSTTL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HMGYCEPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DRTVGHEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WAKWDGSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SIWAQDYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CSMHDAIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RQSCIGFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VVKVSMTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RGYNEGMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DIGMGKND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FPVYLQSN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PNCKMAYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NEYIFAVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HCCGPING.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HNMCYGGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GCCDYADG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PERSIDLA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PCWWDIYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RWYIMKTK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TMLFPSLF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HYYRSKGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VQQEGSEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IGSINASH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MFLCQTSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YLKWHPRD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NWCSAQTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TSHSFARW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QDYICDSW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PCLGVVQH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RDEPGGEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VNMEVIQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TAAIKGDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MYNNINYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VSYKDSDM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CPIDVEVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IHCMRGIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DVSDICFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DQDNPWLM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VLIADNNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VWCKDKCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RAYHTEVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LKCMFDYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WAYLCWDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HGLTVAPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KTGQTEPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MKFYPVGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RSDTNHKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RLMVHYHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MARKTYEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FRIKDGQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LLKNFNWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EVRCGETW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FQYRCKRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EYMPNADT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VAKVYSDC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-APSHFWPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MYEDINET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KQMWKLVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GCKAIPCM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NYAYYDGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QWCAFTMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DTQSPTGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WVMWWWLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YPITFGIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HPMWWYRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WSRLTDSF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VSIHCRMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FCIQRGLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MCVGMHCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ILGHIFCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LPCLDIIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CWEFIVVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-APRFIHFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EEDIKQGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TKVMERCI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PWDAEALC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RQKVELRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ACKMPMIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PPKWEGML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MVNHCICC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SVDIRECM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WIGATRQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WSMFPAIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LGTPARWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LNWCDKRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MSYNMNDQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MREAWVRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PGMQCKTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PGFNVADY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EMYTFKTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RLAEITIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WFWFARFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VPMYVFMS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FEFTMPNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AQDEILDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QEVALLSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WQVFHIKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DISLMWCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TWWNCLAM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WVDIGPES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-AMKIMHLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YKNGYRLM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LNRQIFQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KVKRHYIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WPDDFWGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DSPYWFNC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PRQSCWCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VIGMPRTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LNRTLIAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MAERWFTH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MACPFRES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RNGLKRKD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RCKFMSVY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EYYWVLGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HDAGDFDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-KGPWAMDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NWDYVRHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NFAEDVYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FFHIWTIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WKYNRYMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SANILWIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DYVCEYVA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ISKLTKAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WHWNADMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QHVDPIIP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YVLTLFFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WSHGPQTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WVEMMNIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HDLEAVGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GCRGSNYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PRNGHCLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MPAGIEPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-QLTTISFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HWVPQYYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WPPESNQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GNIEGSAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RMECLILG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VPVCKCGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-PLLSVVKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RFEDCNCN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FMCVATEC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IEPTENMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GPVMYPPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EYLWPQDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FNQPKYCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RHAFKQQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NAGKRKIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DLEHMSCY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-YICLFNFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MSRDPDGR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EENCMLCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-LPNVTISV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NSQASCYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NCQTLPPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HLAQFGKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TCSNFQCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EHKRKNHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CNEWTFRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DCNEIIRQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ESVQPNYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-WIGFRRMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HPSVLSHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ARSHTGGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-CQWGCYDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-VVQALQSN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SIRVPLDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SEIWNLKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SINSWMTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-FDHYAPYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ETMLQQQQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-ITRFDDPA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-IKRIHYRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DTGFWKWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SKGHWTKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-HDYYFCFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-MTGNAWTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-GDILFENK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-RKQHWHIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-TEGSWSVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NNQMDTEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-SYCPVNTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-NPTCYIGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-DSAKQAIE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Tumor
TUM-EQWDEHLS.tif

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WMCMHLQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CTKPKHIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FFCMNPST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CSNRPWVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HISPIPRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GMHNQSDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CGINTGTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QCGKLDLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SYKTNTMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-ISKYFTME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YSPKRCME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-RWEAGYEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-ERSSPEEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FNYNCYRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WMRYYMTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GQAGSHRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NFHSNCNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QHCLVEWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KVQHEPDY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YNEETRVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NVEAGHLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CGDWAGAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DLAPLDTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CTWVRGFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KCTLKGIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CPNSYPGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HEMLTLQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-ACECYVHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GFWSHITI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CDWTKLYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LANESILM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FCKKAHNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LPSNPSYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FIEDLDET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-AQHQHNMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EEFMQCCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MLISEYDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-PTPELGDY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-PRGCDFQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-AQVGWAVH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LIQNGAEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-VGDRQKCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WKPGPILQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FRWNREWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SCMGVMIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WYCMPMSF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-RCNNTGMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IPIFNVYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-ENMIDWKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QCMICRRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YQICTSHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YAAADDNL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LWAWQWSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-APQIWRWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CIAIPNNN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NTCMSTPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IDAAMYDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-RSYHCHTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FNPEDSNP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-RPCAILRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YWADFKRQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KKARWGEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SNWRFKEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NCPEASFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KCNFQWFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SDFCCHKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HDYMCCYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GTYYNLYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SFHLKIHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-PHVIVFSS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IRQMWPGS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NPEAQVSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GMWKPYCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EHYKMAQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-RTCSMRNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GNLRIWHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QMNQGVAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CQTKYEAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HIKDYNVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DQEAMPRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MDIFYCFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DEGYPISI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IDKYGEHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SMVAIVQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-AKEAIRGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-STTINDEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EARRIQCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SEQMGGTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-ECVDEIPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QDSACCND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SSYGQQRQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DLDYGHAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KSSHNMMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WFVLFFTL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GKWHCYGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YQFEDYAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LLRVLMYN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SMEGDVAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HGCEWYHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MLDPELMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CDLTDGKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EGDLFFNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KVFQKGEC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HLPPHVNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SHESTKFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KNTPHMWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-RMGIEQYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QLWNLELS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YWKMHKPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HRHDGENP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KMDNIYKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QHGRDSVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LVEDECEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DHYIHMGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MFNVVARK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YCNLQSHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FQCSEFLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IRWQRMDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NMTYSILY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FMTLYKCI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-TSNCWYRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QNRNWKNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DTIHFSYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SYDHEPWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WWQMMVNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FCWMFVDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HGAHNGYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IDWRDYYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FFHDDVLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-VNVLCHTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LWTWISFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MYVQFTWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MMCEAEYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LEYRCKQD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EHRFEMWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EFELAMQA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-RFTEILKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-PPWLGYES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NKQCDNGI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MRYEIFMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YNWHSTVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LWFYCMRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NKLFNYNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CHISDWCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GMGWFTEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YMTVVFWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IYQFTGER.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KCLCSSYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FQVSHKSG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FHACNVYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-PPSDLCEF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SPFCDGIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IAVVDSVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KMSNDQTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CMNLTFAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CCSWAVIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IRQWYLLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MHTKPMWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-STKIMDIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NMYPNWGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GNFQEFAG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-PWCQPLDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KIKIPAGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LNANGSYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FCSHMAGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IGCAQHQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-AAGSPDQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CFTWGSDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YSNKDQNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EPVCRDDM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WLETKVYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-AHWAQEHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-HEVSNKHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-PRITCAPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-TDVKVMIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NICMVTII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KKWCFMNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MKPVMYMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QEQTHTNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-VRRVYWDY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WGWITKHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-IESIGFGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DCNGVNYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EKDTWCPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DSFHINHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-FWKQETSW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CGEEPQTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-SRACVIQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-TWTVGQHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-TIDGKANA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-TLQICAQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-YVWNFLWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-ASGTCDHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NSLKSFKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DFGAKDPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-CPCIARCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-LKVNDMRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-MNQRYYGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GDIKNHDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-GDELWVLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-KYTRLNIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-TYYEYECV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-WCTIPDYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-EEDGPCCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-QFKHQWKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-DEGQHVFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-TQYGGYIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Debris
DEB-NGGRKWYK.tif

LYM-MWLSFPGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CTEEDKLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CEQFYYQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TKCYVFRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NWCNYRRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VNTCFYQY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PWNVSFML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RANMGQFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IFWLHVEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YDWTHNMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VGCMMSNN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VVYEMCPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QANRPYSM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MFQDMGHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TPFYLNPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VPISWSDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AHGSMMWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WYIVMQLV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HMSIMRII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RQLLWQKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QDWWHTDT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VFKSFHMV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FTTRYILK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GVPRVAGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CVAWANVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TNMCWACT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VDRDSNPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FKLSDSTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IDPMQKMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CCKWLWMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ASIYCTSP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ILCASMAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CWNRCSLH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HVFDMSNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NHSLICVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LAIRNEWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HMPNYPTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CCHLHNAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RQILAVHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IQYTTACY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VRTFVHRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-APYNAPYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QKYVSGDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LIDTETMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LWDHSVKD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TNTASTME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FQQTDQLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VDMRHMIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GGEQKNCR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MVAIIKFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MSPDDWAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WWHIYWRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KIYKDGLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RVQGTFLV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EVEVFRNM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PESGQHCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YQEKYMIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LTGGRLIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FPRWSQSI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MNFKSCQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DRNEFNIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NVVALNRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MEWIAWCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NQDGLYRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RDMVIFFY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PHYTIGIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WGLQFIPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DGDSRGPL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CCYPERIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IVHWNGCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TEAHEQNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LAFNEQLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ESHEVPRW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TNDEFNCE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SSNSMYYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RVYYRPGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GSSHGIQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EAMCSIVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MHAMDDNN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PGYGRTLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SHKCFPGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VEGHNYRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NSCLWCNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PHHKVCAF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KSANVTDQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TAMECKSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RRINHDSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WQLANCLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PPASSIYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HRVQKEEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WESEKMTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VVMWEQCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SRWRLPWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CRVIERAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CHLAIDTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RGQRYTIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PLDRWWKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NTNPYWIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DTPAIWGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LNLEMADY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DLYVHAPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AVMYIRYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MSLYIKKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LPSLMAHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LRILISWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TTSGHCWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KGADTNIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VQHQGYQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LVMNSTVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LPVGPMEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MDGKIEPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SCMRKWQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QFFPQGYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NAWLQGTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LGFVKDHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HGAHRQYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FCRWVKKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ASMSQTTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LTNHANQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CTIDVTWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EPLHINMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YLQITYES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MAYCSLIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MTSLYYKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WLCTAIVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VRMDWHCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FMDERWNN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EQCMCDVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HFTKCVLA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SQYCSYYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PDEKPICF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WPQTYMKA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FKDPDFHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NQSRWVMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PHLFWPYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SGKMCNPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KDPGPSTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KWTSMNWD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NQYEHTNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MPVKLDGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IGFCLYNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MVAREHLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HESTEQCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LAGYNYPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DPVNKCNM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PERAIKPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SCLDAQQH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DGERCNGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CVIRCNDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NVSPLTNN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YLMTMWQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SWGCKAKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TKDNMWYW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ESCNNERF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-THEVSLMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TALNDIQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VGTTVYRK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FNENALSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HHYRDTEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MWTEHSIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YGHFLWKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NNWTDLNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EENRDCAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LWVQYTGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LCDWKGNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KYAKLIYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FQWCYFGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QGVNNHFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AGMCVDKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EQFRWDNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FVVCNSLK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VQDKRECG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CNIAFQHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TLPCTDQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WIDVYILH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WDFLYKPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LHMWQMWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RNTNHQVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SKCMLYKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ESFEGKNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KYAQEPMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CYDDTQPL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ECTGKDRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PVEELRMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ESRNMIMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TLKGGQHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RMYSNVRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IPATNENE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LGWHAWVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PRLTWTQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NQLAYAPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SSCVHKEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GTHLVDRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HTNNHWPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NIFWVHQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NHSLEWVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory

/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GCDGTTSP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KRLFYESH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GCPQYRTI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HGSFRATF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FVASNQLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MRMWGTIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FPMNMNPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ATCHCNFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LVEHNKNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AQHLDEMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ILGCSMQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VNAPCIQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IKICEDTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YCNSWKSC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HCRYAAGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IYNTRCVY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ECQSMKPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HMVGQLRW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DDLVGNIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WYQDDAMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MMEAWQWV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ILAMDLVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RQCLWSSC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FPTGTQYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ERRMKLHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TVSVPPSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FCRREDDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QTAFDATH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LEVYSKRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HLSGTMFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FFSPIWNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QRPHTCSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TWIDCFIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WQDECQPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LTIVINWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LTRWPTHQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KSMWDAIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GTCLPRHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FSGWNFNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IIISQAYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AYWIWDEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RCCHTSDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TRTCAITV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RGVEFGVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PGGTVFMQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DHDTNMSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AQRVHASR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MDQNHNSW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ARMKMKTP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NSAENRHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ASIAEYVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WINGDGGS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TIHMRSKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AEHKCMNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MRVTNYMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VNKHICMV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DGFWMNGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YYEDYGMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RLKEAKQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YRLCGDDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DLDAFEDS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YLYNMESN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NGPAHTCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AEQNELYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YYTHVDQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SMEMEKMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EMCPRRHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AMYINIRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EYIQFEIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FILKSVPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NSMLANNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VFHAFQIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LTHQPFPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CQSLQIIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RKAASKEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SDTTHGAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PRENRAMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QRDFAKKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WRRKDENP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SICSEAAD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LNAMSNCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FTFGCPTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HLIPEPLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SYPLDCCN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HYFKCRRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VMNLHYDH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EQWSFKFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GLARDCYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DMMELECA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PYSMFWKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WFNGCCDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FARFCCDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PRPKNHPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IQWVHNLF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ICASCLAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VIHMEFHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CNRGIVPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NHPWDNQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SAQKCYPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KALNVLKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VCFNPFRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DDKVDVHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PLAGGGYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LFMSVKQQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NWKTMFWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IWWWWHEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FNIQEGRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SMTEGLTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MRYWSRGN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QCVMHIDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WVPIIECF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LQRYMEWY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MWCQLHMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NPTVFRGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PQFGGFCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KVCGWPWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TKFYDGPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CQSNPWGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KHDLFQCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DGKRQNRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PHKSMYEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GGDEMGNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PTCFKKIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IRILGEVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-THWCFECD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CVDRILPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GLAALKTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KQTPTETV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HFQYWPWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QVHVLSEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KNWRNEDQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DAHLGLHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GFGHFMAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HSGLMIGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WPATYRMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MQQLEEIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NQVRTWNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AMYWPGFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PGYNSTQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RPWMLFML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MRKNWRQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RKCDLVVA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MKIPAFFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TNAPNGMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EHCDFSFS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MGCIQYHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NYKFLAAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VSHFLLNK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LACTMMNV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DDKLLHQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FKIWICSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MCSGVKRK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-REHFNVLF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HNEKGREI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DLYRVWME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YAGITCTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YHQCDDMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-APIRYWQW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PQYFHSVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QDHPIETT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DDMIHIIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EIWMNQQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CRDEFLPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MRFWWAIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CMLQFYWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YGNNEFAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KEHMAQPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EKEAKSNK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NTMGCNLH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VTVDVSQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HPLAGMDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SDAFVHGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YCCGYHVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LFPHPTCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NQEKVDDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EMAYFDTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SWRLDGVE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LNNCFCSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KTNQVLRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EIRVDYKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YRVKTIIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ADPEFRAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SAEGMNYF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VHWCEAFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QWTQKLLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FLPVHAWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LSMLHRHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RYFTTNGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IAQTPWSS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SCREGRRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IQLRVQSW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TTQIQSMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IKCVKIRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AGKMWYWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CFKKNHTL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DYMLNWSY.tif

LYM-CYATNAPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SEYGALFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TWVSWWTV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NIIYDSVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AVKKNDEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PGRWHRAI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VQQHMSKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HHVYPPTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AVIRQQPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MGCQLQSN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TPCPTENY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TQDADVWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RAKFMVKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EVEWAAHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YMRITKYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FTYIRCHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MIKHPDVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MFTGGYTV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NCHKDYEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YCPWACTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WPGTFTND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LFWYCSLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WWYQFVDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DRVKYQKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CPKHMQPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PHAMPAFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MFNGAYHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RCWCETRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VFVWIECF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NYGFWMRW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EAHKVCSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SPTNVFSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RHQFMSQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RASFYISF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HDERKINS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CANTSDAE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PFDFIQFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ADMAFNHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WYNHNKGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NNNDFIST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WIPCHCYW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FRKQVIIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AKHWEDFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WFLVAVCC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QMKGKPQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ENYWVIEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ITSCMYTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VLTWQCVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NHEFKHLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KWFRFATD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TMCNGKCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FQRQCRKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CQWRYQRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VNCMASQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NVFKPDHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FTRMAKKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TEPYCLCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MKYLKIDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LEHWIIAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NARDIVPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CLTKCGET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HNKGPKCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AYTYCTSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CIPCGENA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CLIKPNFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LYSTWFTP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KSSSYKPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NNQCDDGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WRCEQKWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RHWHDMLR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MKKQNVEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QSVQHHRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IMGQKETI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YKWVMKGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HEHVVVTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YMGKCAYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GWWSEMQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ICPYLWQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WNGWSNWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IIRVKYTK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MYNGIGDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QEPMFFIR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QFRIIMDS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PFRMGDMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MCKMNPGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VTEGSECW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MISYIMAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PHVLPVAE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LAHSMNPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HYCFLHYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QNRGCSEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WNLYIGTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AFQPGHWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NSAKLEGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VNTDICGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PHLEIHLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PFFFCFPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TYELTYDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CWQIGVMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FGEWQVDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RICGVMWD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ADVHKFQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FEPTIAHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QYVEALMQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QNGIPPIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RMMMKGGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EWIRSCEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TVSMGWYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QSEWCSFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HQHTHNAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VRRSEWGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TGKGQMPL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VKLCQTWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NMKTLLLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MHFWCRNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VVWVGPMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ERPPPIDH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SQTCGHTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NSYHFLAM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WKNAELLK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RYRAERFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YFAPNHGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CHRGQFCI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MARNHEPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HGAGDDST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ETIFPFAG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KCRQDTYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ECENCRCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MSHHEETC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TLIAHHVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SHTMSGRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WNCVKYRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HQNFFDAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DYIYFLWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YADFNTCM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SGMGLYFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RLIQMRGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GPWNRREA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EQRSHRRQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QPGSPCNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QECIGGLH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RISDHNYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VLRMMSDC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QDMGSNDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HMSNPWSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YMFCMNNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MVYFEDTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RLRVESQD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HAPFCIVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CKVNAHSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VSGPRERA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FANLCADC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YYWFGGTP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AALKPLVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HGYQYTIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YKVREMSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KGLMRPYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FRNLYKET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YQPLHNKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WMYVMKEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QADQILYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CGKLYDMQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KIPFPWDQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SKQAISNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FQDNRVCF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IVSKGIRK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YKARNGRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NMNDDDFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QETMCGRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EWCLGRKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KHPSMCNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-INTVFHHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YAEGRFPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TSEYQFNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QYVDIGSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VLLDGVIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FFMRPCKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FDMVNINL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WFIRVMAH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RLFYDAVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RTVCNQLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TLRMYKYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KMRDYLCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MWDYTEYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RNMTSWEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RDNDAIMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FMDKDCSS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RPAQPLKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QSPVWFPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QGYDVIIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CRNHACVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QKEYFGWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QWSMVLAD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KYRTVVQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QFCRAVEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LNNFVFTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory

LYM-FSTWSKQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KWDVKCYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IKQYEDDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YIDLAKMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LIYPAGER.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GCHEHWQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WAELKEMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YIDGDPNV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DWICARTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YQTHQKSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QVKEKGEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KVHRCPGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VMMFVRKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DLTATNGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LGPEWNTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WTMWVIFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ADAMTPGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MLEHVVWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QCLPKLIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QWRCPSCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HEWKCSSF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RKHMYLNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FCERHCDG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VQGSDPNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ACSPLRIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WGAKPKWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PKFRHNIR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VCWEDEFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NYVFMKQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DIDKTRPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HTKEGGGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WQTGEIID.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NWTEMSWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PSFEAWWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HIKDGRYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MQIMHHRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LFITYMSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PEEAFMVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RSNPTVQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YFTDNYFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IQLNHMPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LRFPFEIR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YYCFPFNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AFSIMLMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GIPCESVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SCDDPFNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HLSKYNIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MNVQATKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DYKMTQAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PDGQWVAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YDTGSKTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WFYRGSYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EDGDRIYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YYGKGQGN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HLHFMYIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DNEPWFGN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WHRFLFCD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TYLQRCVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ANHSHTEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NYMWGYIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FCPANMMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DNYWTYDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HLTQEWAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HGCCCAAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LASAQVGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TQTHDYDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MWAAWFSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VSDWPSHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QQKLRIAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WQGNNNIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MECPTYSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DLQMWFTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FSPSYLQD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VVRMCYHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SKGLQHWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TIKVLVSM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SEEYPQRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TSSNYSFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FNCLHDRC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SFMYFHIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KDLWIEYW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KMCEEGSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IHKCQLSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SMEIQHNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TYRASMSM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YNQANGAE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PAIDMVRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GLCRQIYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HSVAWNLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HEPFYIQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EITGKVKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QVDGHFYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DGLFIFEC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GNCQDYTL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YVQMTCFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YMEMLIKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KDYEEIYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HFCLWTMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HSDKVKFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ELQEDNHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TGMMTKVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SIDFVPAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DMISYPFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DRSQPPHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CDINIGHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LVIDNRAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HGYYLMLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TNNQPGTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EGPFPSMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NDTAIRPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PGGDYKLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HNTCAMKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IMCAIFLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NFCSDPGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RPGSNYSG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TWMDRYPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AFRIPGFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DNHRYVKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RQYTDDPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ALSQMGRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QLDEPFHH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VNSAVNFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ESRMPGEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VGENRMCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HWEMNMSI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WLGRYQME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GVPSNLQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DCRAHCEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SYVARAEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HFARPHVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WIWYVQPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MVIQCMAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ARLLILEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EIRHSEMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GLGRITTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HYKPFIAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IQQQVPWE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MTPWVWSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RQAKKPKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IWLDKHHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WGMRWLKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YCMPVLWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VDQFRMKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IGYYLGVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FFYRAACS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FIVWHPLV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EKRWWLRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SECHQDFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HSNSSYED.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CQNYEWRW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RINKYHTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RLPTRSFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NPFNCQIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PFMKPNDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NPCHMNGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WVLSMCGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CGCIWQFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MMHKHHMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EYVEELCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LDQQEPMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ERLYLIRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EYALVHEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LQKRNWCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HDVCWQCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YDDRMNVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NLEDVVEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HWKPWLSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IWEWEGLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ECSTECCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VSCLGNKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CCMIDYNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AHNKASTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TGDEFLQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RGRMMTDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RIYICELP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AKWVMHNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EYKAINAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DLWGGCFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FNKREWYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GELPWEGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KLLFNDWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SPCACFFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EPDEMYPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FYARPVDN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VKPWWLYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ATKSYMNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EHQIPQDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DLAGDHQE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EENGFWLK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FPWWDMTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EVKVKQFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QTKLPTME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RWGLYDAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CLYTVTRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PNNWTSAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TMAREWLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory

LYM-QMMMHAER.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MCWFCKFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NEHPWCTP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RVRWHKAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MHCNAGEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HMNACYLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MHTMKHQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VHPDCIAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MKWNNWWV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DEYKRVCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ASQLHDLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DAWDLFYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LGGQCGNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GDCYHPMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AIYKDYFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LPQALKTV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VSPTTVNN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VGMIAFNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CPNPPTFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IWATQSLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KMYKNNSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PRCISLCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TKVAQHKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GYQHGWFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VCNTDLMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GQDSVRSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WRVICCIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FVVVAQQQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MRPANFEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FCCFSQEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IYKFTRIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SFDNWMLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CCCDHIED.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YKEMTWVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KKNCAFWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AKYKQDTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VKEITIVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KVMKQGPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NDALCSFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SEGPINYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DKDRTKNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DHCKWFTH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WDTMPDYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GKCGVCNM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RHSWDPEW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NVENALWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YYKNFRGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AGKPALDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PYGWKSLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GWMRCALD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DYRWRSQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MFDPLRVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SSCTPASH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AHSRLQFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MDCNADYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TGSNRELW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IKPTYIWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VNNNQFHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EQNCGTRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WQLGWDPA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CLHGDLYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IDNADIYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WMQCMFHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LEPANQRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CRLKWSPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PGHTTCVH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NVKPEPQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ITGYKRWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KAFFMFMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FGHNMCRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WGNHPKCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ESKWPGSC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HDHDPMFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EQKEALWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WWNATYPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TCWCDGVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TIWRTADW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DRIMNRSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MSEGICGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RCVQAQEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LGRQMEGI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TCHVSQGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NGLKFFFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GYSGYQPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YAPRSDLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GNWVPWMV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SWLHHMQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KFYNMMMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TATTDDES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FYFEDLVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HWIPQHSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WRTWGWPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EVCHHNCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AGFLVTCE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WDTNFRFR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WEVNVVLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-APDPTTWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VFCRAIMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GYTNHPVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ITCFFANS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PLHWCFEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FNRADFQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KSSDAGTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YGFGKIEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RVAITWLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TYCFLEYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SQCITGVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YVGPWRIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CWEQWWIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RQHDCPGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GANKMNGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MQVHISKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KGTHEPMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FWTSWGQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FHILQMSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KFSMYVWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LNSEEECH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EPSQETYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MRGHLAYN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MCHTCNPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QWEQSQHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MWQGSFCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WELPRDLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LNPRFRYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NPEWANIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CPVCSGCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NFSTFPVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FKFLSFDG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CNRLFLKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TCYEFLAP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MPSWAKTN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NCKKMKDT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-KVWKNCSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QKAPAKKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EGRIGPLH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SATSCCHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VLFFHPVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NYEKAAPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HYMEYFRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-AQHLCKMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FQSSTVSP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EKIQNEKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ISGEHNDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VRGKYCCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FCTHVQSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-NTAAPSVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WSYWTHHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YWEEIWIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PATLSLVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MQLRPSWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-WWVMLVLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SFTWWNKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SSEMGHPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FHTSVDNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RCRCRGRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CSWEQWPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QYNLFLQY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MVQLVWMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ANWDQMGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CDQCGTFY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FFQMVNKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FGVGNADP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-IWEQQWID.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MKSGQSWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FEYELSLV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-ADYSQHMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YEHYCWHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DMYNEIVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YADFEISV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QFSTRAIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-SAYIVHGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-VGVHNCMV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-QFQADLQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MAKFGRHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-RVCNRMFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CTYEFWTK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-YVLRYLES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-GTWLFWIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-PKIHKLWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LFLGKPMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HCVVENMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DLIEYHLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CYFHHNTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-EYEGLRRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-REGYQYAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DIHQSEHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-MRFIIATV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-INYKIMTV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-LEKAPLIE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-FFWGVDPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CACGRMWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HPNERLHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-CRCPKAHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-TQKPWHTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-DDTAFGMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory
LYM-HCDFLDAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Inflammatory

MUS-ACAPSEAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PSMMKWEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LAKEPWST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MHSPMSFY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RDYTYTAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KQSPWHTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LNIECPMQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HNAQGPFY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CCWYQQTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ADATKIDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HLVVYIID.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RCVLGWEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EWLKMCWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MSVGICMS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DMHGHEHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FTDTNNIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RKAYPLME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KGDYQCQA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TRRWTWVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AQETCPNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HAYAKACD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RHMYGANL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RILVCMNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MLPPQGCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GCDAYRPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CCTFAQAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TNKCCSVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LPMGETDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LHKQGLDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QHEFCQFR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ALDVGCFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LIWEPDTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GHKKAMHF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ARFGKCHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CATLDSSH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RSREHQCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VGAASSID.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KHCWIGSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RMQLARWY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CFKANWAI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QLGFGGAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QACQQKGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MHQHLGMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QRCMQRWI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AFQRSEYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RTKDFFRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQQGRNHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HGQLAWIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MHSIPLWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NVGHWYVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HWFVSFKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MYFFKRGI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HEYHHWDC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KSPYYILP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PRAIRHQH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LMVGLKIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DPRNHQTL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MHSFPLWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AKAVSYRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TSSGRDRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FWRSSYWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ACCHQECH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GRCGSEEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PSALHMFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HMKWRDAI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DHMTAYLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PCQMCFWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQKVHRLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SPWERNMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SAHYYCIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KPCWEHNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EMSTYFNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ARNYKVVA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TQAVPVLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QIVVQKDM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GAKGKQFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KMCMYDAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CFTPQHFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DSDESAGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MFTEPSET.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PSKLIYIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MHEDCTMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CNCHLWHT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SRMVPPRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GASGFPQW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SLFQGWRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HPHPEDFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GKTQQFAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KMVITFPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QHVRCFYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PELMWFQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQMPNHHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NCMVFMQV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FFETSDDY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QVLCTMYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SFQKFQYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FTYMRSIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KSGFVAKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LIPPGFYN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KADQQMHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KMVWFIIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NAFPEWPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HDYMDMMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VARRGHDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DTFGGTRQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EQTWGESV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QCMEWQLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KYHLHAMS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MSKCRVLF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FLKTGQFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VHHTWEGI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FRYCYKMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TCDYHEHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IASCSKYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KNGIVSKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CKFAAGVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GRCSQTPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FHIIEPSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FAWFSCRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ADKMALDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HMITSPFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QTDWYQWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ARFRCVWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SIPWQKAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IPIGELVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CNVYKPGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DHRMTRRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MLAILRKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EPCLPPWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NTGIQEWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TCRQGSSM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SAWRLHYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LYFGGYVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SAKLGNMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KWVKKWGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PHFNTQGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KQLALSRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PACIRVKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CMDFHDDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SHVTCFGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VCAWEPMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SWWMMRGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HFRWCHMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NMMKQNNV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HYKMLWFS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MSLKQCMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SAVTKAPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RHMWRHRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MWHTRNPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KCQWSDID.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GMGAGAKW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NEADMLSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KGKGRFVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QFAWMESW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EDQVCIFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HCQRALWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LHKKQFCC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HAHPTWFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AVSYTFSM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DKRLGKHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MEECFMVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GWQYVTVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RDIFLDLS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GKFNKRND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GHDRHNEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RYTREIDY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VLTELAWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HYNPLEVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IEYHKSSS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LATIEADA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HSVDADQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FLWLCWFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IHMHFKCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TLFNHGNP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RCNRQHRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TAEWEIVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EHGPGDWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DEREWLHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KCQLIVSP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PRKRHMNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QLLDNSAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INPENWCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSCRCKPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LMPFTHMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AHYKWVLM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HFMEWHWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ARYWQLIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QYPIETFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AEEPCFCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QCEMENYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TTHCLVYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TMGQPRVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PCFYDRKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MGNVKGCD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HVQEFSDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FCPTKQDT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IHRALFCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LWSAFNFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QWGRIHVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KAYVSEEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AQQRQAIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CSEMCCRD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GSQDPYYW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GDQCIPNN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QKNSCSFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FFPNYVWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SGQNDFLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INNDWRMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CAHVWNNK.tif

MUS-HAVRGFHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NDIFLTKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GDYKSELI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RMGRSDRW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EPAQTYGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AHMTTPKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SSKVTTME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CKASSKTY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QWCVHDQY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MARPPNKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SFEDYDQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DYLNNFNC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NLWIWVHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LMEIGWLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IAHYGHQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MWTHVACT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HQSQSWHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LFTNYIPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HRIWTFPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQCTCAQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NVPNTGKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AFMVMTYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MPCWTCCD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QDEKEPRQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RWPFDPKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TEYLCQQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HPTHDDTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FDHLCRIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KFGMYMTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AWPNMWYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NHVQTTPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RLGGWTEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-STPAAEVW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RVVICYQQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PLTHTNGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DKWAVWLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DPPVNMFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SWGMVPGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HIPHWPWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MGNAENAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GIYFFEKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RHPFARHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EIAHYLYH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SIHMSWNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GWYMLMWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AYFSFLYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GNLDLPWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TYGGYWRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AGWKEGYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AHNHGPAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PGERNTAD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EWRQCDCE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RHKEVDYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NKPPGPMW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PPWMASPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-STERAMGY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KTAAIHAH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PVPEFKKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HVYPRTDK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EKLAWKDQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FVVATWQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HMWTGNHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FNNDMTRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NNNNYEMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CHVWIRGS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RGCGNWYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DECCKWDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SVHTKWIQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AYIIPWSI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HTVATWRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EKFYLFSM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DCFPAWYK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DSCEFYIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSTSWRHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QNFLQWIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FEELYASV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GWCLNAIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DEIRSHPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-APLNITLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MWWSYYTS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KVQYFPDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FQDHAACC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KCHNEWYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EVNWVEGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QYHVRRMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FRICGRIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MHYGVRNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QTQEGVVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NWVALCHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SCHYQYGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VFRNMWFR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HMSATIVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CKDEYPWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ITGLWDPD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EHLTLIVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CGHLPAVH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DYASPQTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PISWRHGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ESHQCNMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GRVCKGQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KFCCENVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FMGKQSCI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KALGHVNM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-APIWDLPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QNDKMKWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SQCFYLRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IHQHDNNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ASCALKIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LSLLLFPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FCFMRFPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QIEQEYCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PYNYPPPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VDHYFPKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PPWFNYKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FICPLDLF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DFFQDRIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CGFAFEWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NPCPGQSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DHPDNKYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-STVKKFWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GCHEAMMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TVRWSWSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQHEQSEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CATAFVVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LWSVEAMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DYTHRKYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LWNVRENI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EPGGVVRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VFHSYQFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VIHLDGYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KQGQNQGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NSVIPDIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IRHNHRLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EMDSEIES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MTWKKHGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HRQSLDMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FTGIWINP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IAINHPYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NCIEREQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MGETKDYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RYMWVPIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HPEFIPTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CHHWHPVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QYHDSQRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQGDWVQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPTHRIAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GNIYMQKL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ADSCVPHM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SMYWRMAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TKTIFMMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IFIMDSKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PWCETQCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IFTAYCHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GFACVVTQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ESYVEESD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HFYHMTSN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TKRFECSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HMLSDMNP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RNMRIITK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPNRPNYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EMIIFPWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DILWRPMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DWNYCCNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SHHQKHEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RIGDIRYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GNQIMSWV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QNEKYNLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MERRTDTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TCLKTRWD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ACPQNDVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DPSMSFVE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RHIRCWRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QYNNCVPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TAFFDGLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IHETGSVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HAWYGITE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-REIPQKDM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LPSGGIFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ANTWGTNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NVPYQTML.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LRERLQSI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KQTVDMSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AHGTEGPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QMHWETHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IDCLVWEW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RCIYNAIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EDEQNPLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IDATAFFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RQFVGMMF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ASGCQCLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NGIPVYII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NYYHTPVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FVFDPATI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SSFQKHPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SMPEFLFS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MLWPIQLT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CGADYMCR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PCDLGAYE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RRGTFIHT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QEGRAVSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NVFDHMPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EFTYVWIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GICAEDNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LQSHCQVP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GSTVWINW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NCTAYGRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FKWLIRIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IKCYWVVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CKWRYDGV.tif

MUS-LAGLRGCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MFGHSWMP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KRLFMNYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FALFRYRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KLWSNNNL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MQMWRLEW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LDLCEPPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SLTDGTMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ELYDWVSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SNLLTHLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TKFAVWEW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SLRRENEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KLDFVTEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INLDYSPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IKQEIANS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PNFPCKYT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DRVNGQLC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SMKGYAKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CKSISIGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MTSVFQQN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KAAYLAFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INDLMPYN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VGRWEHPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TFCQCDLR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SPLNPWPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NEALIKWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SMKIWLYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MFLTMCHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RHMEWGPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EDGCDGPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SIVCMPRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ASHGVADS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSMSRSVC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NPCIVAPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FKVQDFGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VLCHDESI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KYVEMCHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NQTDKGPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FNMKDHTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-THPMCYWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GTHYVKEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KPWRHNRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LRWCYAAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CNMLKKDS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TEEVQMDV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TNRLFNQW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GIIKRVWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LTDLLSFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ICWSCDLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LFRERQKW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TIDSIGGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RMEECYDM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NDIHVGQD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KTSIVCDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INMCMDKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LFVPCLCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RVITHTRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MMDGPMWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TKDFVCTH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NNWVCWEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VAVCWHLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RTQEWARE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EGFFMLPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HHNPQREH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KCSCWSYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RTILWFIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CYEDSLAE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DEPCARFS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AKCVDANR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NDDFYKFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KQEMVADL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RVYKETWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NRSYTQRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KNFYTADG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HRYLWSEH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QMICVGGN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KFWWWTDT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SYKMKETE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KECEIIGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AATIFRMS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QRLWQGES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LWFQMKPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KSSEDTWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AMFKYFTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RRNCKKIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSITFRFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CHMRQSDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPYKAGPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HCSHCKRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GNFRTSGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GKKEHRMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GRFLYQLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RYPQGRTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FPVFHEEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RKHGKRPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QDVKLWHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ICLIETNC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GTPKWAVV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DSLGRKKA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HILRWPRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EHDQTSNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SGMCHRHG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ATSLVVCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DNLDNEKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RRAHHYYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FMQKQKYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IRFKMNRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GDCGGNYC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PIVTIFPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQYYLHSS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CPPPDYPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QPSKEQCA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FVRAMHCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ERKVAMSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NSHSQVLD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DTYDVQKM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RISVCCYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KMMETVDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KVFWMPGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RGKEWRRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SLPRYSWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MQPEDMLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NYLIHYGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PHDRLNNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RSNTPHWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ELRFVNHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MWCAAYMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CQKMKVYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SQYPKQWE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LVSNHGIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MCEVWITS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KCFWHTGN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GQPVRLQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GMGANWTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPNYRNSP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RWDDHMVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RMIRRCFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LMLINEKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MLKISIHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GHEEQDMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ISTCWVAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HNVHPWMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QHSLLLCR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HVRSWWGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PGHWHHQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EEDKFSYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HDSDWVPT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LDQDTSWL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LFMTESPR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SPTIDMMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GQTYDKYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RIKYIRFC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FNSVFYME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MFKCVYPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MSLSCWRL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LGNGRPHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TWLTTLCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NMYSISFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MYALMDSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FLFKYWAG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AWKSHNEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PFWPMALD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PGEIKPKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MQQIVGPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QWTRAYSH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FNDDCEQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LNQITEIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VIGEGPRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LEWWIPAH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ERIHCMCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HYSCSQDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GTFGVIGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MCAQPHPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RKDGKYPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FKRTNMRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GCSNCLWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PQQLLLDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NYMYDALV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PTKQLNSI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QHICNVTP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INGFIMII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CAFQWDIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CMPHCWDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KAYTAKHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LFGKCPMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CIQAGCRV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NPLRWNTI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SGNITIRV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TTIYTQSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HWFYWYAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MSYTGECA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TQYPLKCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GAGQTWHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MGGKDQHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DKQSHSNH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GSCGMMKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GDLWAVLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EEKHIYHK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LVRENHKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HHPYRAHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FYDFFMFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NNESNVVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PPICEFFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DCMYMVEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PAISRYKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ECHDDLYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VMFGPPCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TDHFYKIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KFEIVWNL.tif

MUS-RYVTFQYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TCAVSYYW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MILAMHNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HYDLVTME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GTCTVDQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ADWILDYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PMHYPRTV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GWHAYAGW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RDCGVTSG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PHNVAAHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KEMWAMNE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EVTRFADK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KIANVWTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MHLVICIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LPARMHNC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AQKTMTSF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RWHSYHSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RGNHSTDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IERFYCHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EYAQKMNW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KDWKCSFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HMDQTYKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EVQGAQEM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TEPVIACT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ANAAFHTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FYMPRGWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TSKLSKAG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TMTYPGVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LKLECYVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FHCHPLYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CHGYLNKE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AHFWHGTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DTKEKRDT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EKHLPWSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QINLTEST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LFQHQIKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LAWSQHQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KHERTWTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ADTKCALN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QDESHWCY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GTHIFAIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ANWEVNNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KIILLWCY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LVWVLDFP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NLRNWDYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KKSNGHYL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LIQYEWKW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TPPLIFKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LIYYALRF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CMKWVGEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CLKFVEFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ICLTDNPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PKGILAWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HGFWTCGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MRECTSKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RHWGVKCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-STGKADAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DCQNYDVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MINLHTPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RHQREVSG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RYCRSRLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ILSGHVDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SSSHRCFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TLASWPWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EPLWTHFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQRDSVSP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INASIYPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LHYMLHIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MIGFGYPN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VDKENHSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KGKSFIIR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FFCVIWRV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FWNEFGHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NPAECVCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GESEIQHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PLPQETFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MQIQVWKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EHSRSMFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSCIENVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FGREEINI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QLMPDGMS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PDMEHWLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TAGTVEHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GNSSEQQS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HGCKYVNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MDCWFHCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EDALFWHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LGLIHWMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PTYLWGVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ACLQRFRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KQQGWRRH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AFSNGCTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FKGMDRPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QCDDQKFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LSVERCQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DNGLMIPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VEATLRPG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RSPRNSNC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CMSIWAFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LHEWLTQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GRTHCGYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HNDSSVTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AAVLKVNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QLTTWVHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPNGSIHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HAVMTTDT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AAVYIFRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NISSWIAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EPMWTIQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FIMHPRGE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MGKKVRGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LQIPFFLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KRYIIQTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FEDFLLMT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CIITQWPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EMAEQSHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SMFCFCYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HYPMFIQM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KFHSFSPW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ACLMHLYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RTMLIMTA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VCPLCVSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQDALIEH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ELTVGLDT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VLKRVTFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RRWRAHHQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DNCGTGQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AHDTETPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GGQETEGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DDFGMLFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HYMWFPEP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSHKGGWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SIDANKNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PGQRAHMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RVTELLKD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CFICEINA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CVCIKFKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSMEGHHC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EGHHRVQP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ACRPNRIK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CNMSICVA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LIKTPDEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MDCEVCWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TDGLFLEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CLYRMIHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DFIRAFAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LTEGYCWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NQKVMLIF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MQVLDAWH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DTMKAHHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EAMIWRLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GVATFCNQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PSVCWYFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LQLMQMDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EFFCVGVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PWQGLAHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GFDLDCLW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPVHKGAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EAYICIKQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NNLLISGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KSCLGWEA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NKTSCYKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AIIDSKYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MEWAVMCE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ENWAWQRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DRQKGGGF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QYIWKNDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ETHPDLPK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DYGFLYSP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RCPECEVN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MRAVESVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PVHREYIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FSKSSHSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ISMQPKEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FIRWQFLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EEFNEKCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KVGQGWIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AKKIWHIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KDYNLHEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NWPGADCT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RMHHCIRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KLNHLALN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GWDGSTVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PQWKHWQY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AGNTCNEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TNWGGTMM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KKIRSSYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GLKEKGNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GHMPRVFA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MYDIQYVA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CYQCYKFL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TWRGHRTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PGATSCCF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NIAPHATC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CVMFEVIE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HVRVQFFM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TSCHGFAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MTMFKCHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QPAFHHCP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RCVLDEVG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PFAVIVGQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IFAPCFRV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AWRAQDTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FFTGQYYG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TTVPDHQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DKMPDSQW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FIYLYHCE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HEYCQTLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NPGGKEST.tif

MUS-PQNRCERI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RNHAFNMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IGLWNIDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LKHCPFHN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HAHNILMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TIMVDFPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AVWRTMYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IAPDLFSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CLIRRHIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VAQQASDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CAEFPIAL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DYMHVFVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GCPGCLDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HMYLVEGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DGVFTIIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KDHMVCRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LHQEDWCI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ANPRHYYA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RRTCNIRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DPEKKTYW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GWSWPTSE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TRARPCSY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PQNIHCHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LREFAFIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RVYEEEYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PEKHASFG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CLFMVSQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AGLQHPRR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SILMSWWS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LEDQLLWT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FYDELEWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LDRPWVRE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LVNCQETQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CNSFWEKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MVFVVAII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FCVRRDNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FGEVDMES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IPATQGSK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NAVPRHYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HEVAIHNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QPCAPRIW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KACFPNKW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KSGVWVEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NMVYNHAQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NLHLSQSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SFMPQGNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SEEMRFTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QKIEQVSR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AGMWRPVT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CNDMWEGL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PLQENPYY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TNYIIMDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CSTWAHKA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FQVDFDPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AKLGDITM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IKTEITCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LLMYIRRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CHRIVYSW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FALCDKQR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SYKHGLWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DIYRHTVM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TRNYVCEE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VCDRWGCF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NQIVERPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DNSSTLHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HLQMQQVS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CPDRSNDE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LKNHVKRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HQNHMCAY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQTWMCTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SNVIFVEL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DSTTHVPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NTKRWHAA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VFYNITRV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PGQMSGPC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSQYQEAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MMGVIPWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SWARYKKY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CLQDTRDL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SQTSDFFH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GVFAEPIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KNKRKTGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IKMANDID.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FAKPQYNY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IEGGEWDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GMFENINW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SLEDASIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KWFVVYFD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AFQHITPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RDTQAWPA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QMHLTFLY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PLWYWEII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FVGMSDLF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GIAQWTMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AKGAPISS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KWGPSLRY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QMFKDFGK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KDFEGEAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AMFKYANS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PHGLVMCM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GYDDMYKV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PVCNIGHE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HDTKESIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LNHMAHRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QHHWSNFQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HKTFKVIA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NTPHSGWV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EYGIQGTT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GFTINVNI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CYECRSDR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CKLSLDHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DQFCAFII.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DSDFITPF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DIILYGTF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KIFESYPY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NEWYIKRK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INYPTTYW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SWLARCNV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ADRKLEEN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NTMCVMMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RMETVVKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HKWQNHMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PDWQILWV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QFRLFDKP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NWRHQHVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IQHCNCVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SLLGWTEW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IHPWMQQT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HCWFQRSC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QGEDIPTG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FLMEFCPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EFAGIDLV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IDWYVQRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TSVPERYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TWWFGFVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FGFIGMRV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TCWWQHRA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ASIRDDKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VIYVGDYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QYTQCMHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HSFTWHSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DGVSYMNN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RWPPHGLQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CPRMTESE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EVLIGRGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KCCMDSMA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SEVHSEHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ADGSKATN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TNQHCEDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TGWTIQYP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TKWFHEAK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GGWKHQGC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CGDTEAAR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GDTYTPDI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QDFQDVKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KGQLTYMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KCHQGWPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LYDWFNCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MSEAYFTW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IGFNEQNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ASSATWAC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GIRDIPQG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QMTALIHH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QHYMIAMR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FCQGDRKK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SHSWRLHV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MYDQVHTV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QCSCGWLF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CFKQRVGI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MFMHQMDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TEWDTSMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GYWQGEHW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ELFTNSMQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FWGDNFIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MVVFVIFI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QTIKIKEQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GGHWAVYD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KNVTPVLP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PQVPCQME.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AHCMHSMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DPCNIYKD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MWGHGEWA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QYIARQKH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TCNKMMMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SGLSEFLM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FYAEVMMN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NIHTWPQK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FVWMLEFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HKWQISFW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SPIYLYLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LQGRCPYS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MDKVLWRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HWAACFIG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HNEYDITK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QAWHQGQF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KNGPLDIM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SNMFIGFT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HRMVKWEI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KGYEEHWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PEECNAVQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SWVWCLFR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LRIKPNAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SMIEGAKG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VGDTMNVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HLSCGPKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HITCPYNR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EIHRHCKD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NQEDRDIV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MYQHCHVS.tif

MUS-FGLRECST.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TLVTGAPP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FQMSEFYV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PYSGCHTI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DKFGFAYM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TPDFIKSG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RVIYTVWN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LNYLRDNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KYKGRQAW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MGFTNEPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HCQCVKKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RIDTEKYR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MRNDVNGP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GEEHNRPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MWVRIKKT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MANYEDMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AWALQLCK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RWASDKHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IFSWCEWQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RDSNQAIQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TGECRISW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SPILPHPM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GQQTRITH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PCDKIKHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RLEDAMWF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LWQRYWEG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ARLSRFVK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SCHTSAWK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TVRPHYCI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VGTANLGD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GIPLWDRM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TRPAAAVY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IDLPPGWP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FCEPVNQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SQWASCSL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FMENNWGV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ALKKYAGR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TSYHVCGH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HNREAITA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QLVHCMMG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PVYCKASQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LQENQGWC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GHAPLRGG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NWLVHNCH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPCHVRSC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MSEHMGVR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KEEMREWW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SYTYNKGT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HHTCQYRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TKAAQVWR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QTNGRYCW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FWRWWNLG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TFIVENSQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KSFLDCIT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RQTEFTGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MYFKQADM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LYCKKQAT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HELNVNCV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HGEKHFKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GFSEHFCY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CFQSEFSV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HWICFMCE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NECWNTRQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HYCVRSFK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PGYWSSAV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AIHCGQLR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GRGFVTFE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DVLCCGTC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MPQTLQCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KASLQAGI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSVYLHTH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DLEGESLV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PVSWWSNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-INKHTVCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NMYHHTKA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EQHKVVIN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GPTVETVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SAFVDYWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CGPFFAIS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TNHNLQRC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CLWIFCTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RFRNEVWY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HVVACSPQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPCVQSCG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PMTSMMVD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LNNTELHA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-IAIWNFSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HTEWEINM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KHMWGTNA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CRWIGIIE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ACIHIEIL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SRQSYSLI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VFIKELPH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DMNGYDHR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ENNTKNMY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RYSMNHKF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MTEYIETW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HGHHNTTR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TYYWTKNF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ARQNWWTP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HKWDNSKI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MHERTMEV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CGMLALNP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FGKLKDKR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PRAGIDYQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SGFKVMMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GVLTPTSA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HTNCLDER.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SNVSAKTM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SHMMRFPI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EHLRTSRS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NSIENVHT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NEQFVAQY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HSYKDRMC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CNKLPRNS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-THACGDMK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SKLEYLFF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DYIGKSPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VEKANGLE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QMWMWFPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VALPGYFN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DCTMFAKS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GCDDCELY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GDMIPVWG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QLGTKFTK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ISEDFIHD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HKNTWEIP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MTKIFFGM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DDSPSDQL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DNIYKNQI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HSGFCPDW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ADIFFWHY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KRHREQVL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PMGQKSIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EQWWSRWM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KNEIPVKC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QAHRLYID.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GHFLINDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NVAYPWES.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RAKEEEPE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QLFVITSM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TTAHWWMH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GQTQKWKN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CNFEFSTE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TGVGHSNG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TMMAFIGW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QHMSPFNT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HPQCDMIY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CRKAMAEY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KDQWPLAN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NFMEWVNL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NFWGYGDA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QKKTSHWE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RNAMNNAS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CGDFLGQC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FCFPRFTD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RPMMPATD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LRHQMSRN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LGHLNKCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DESCPTLL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GFGRGLDS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DGQFCTCR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LLLDVQSM.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KKWRHFVF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TKQTSNEK.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TVFEWYCY.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-AYCYLLRI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-TRSRYHIC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GELSSICC.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CFVFGHMD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FNKNVHCS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RNLQFPDD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NEWNQTMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KKNPPKMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CMNEHPLN.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-ETRATIFR.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QEHCYEVI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FFMMENHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GWQPLHSD.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MCFTWHQW.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-LRRYSNGA.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EWCFPFWE.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MGMFTVHL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NKRVDGNV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-NWEMQKRP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-KNILFMCQ.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HAWHFFCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-VDKWLPHP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SDSICWPL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-MNCMMMDG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SHARSKPV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FQQMSKRT.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HDDISRCL.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CHTMSIYI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-SLRHRDMV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GTPKVLIH.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GICIKLDG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EASYHIHI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QLLDVWNV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QSPSHTHS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-FLHMVPDP.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-EQGWDDFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-GVQRVSFV.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-CRAGIVRG.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-DWFWLDND.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-HSMFFMPS.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-QVVSVKMI.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-RCHMFQDF.tif
/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Muscle
MUS-PLKDAMIH.tif

In [8]:
data_record

{'path': ['/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GGYHFAVK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-ECPVWKSG.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VDCVCPSP.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PEPNIHAQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-IANDFGMH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GCEIRVHK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YSSSWGGT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RQHKCEFV.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DWICCYVY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FRELQPGK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QDLYQASD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CHEGSMLW.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FWIWKWMK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VEAADKHF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NGGYPIFE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MGQHQFNK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VLQMTLQS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CHCGYHEC.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MEFRLSHA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GSVVIWCH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-SNNLPQWY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-AQSIRAMI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DNQPHWHS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YKRLPGCR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CHNWNPWR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FYWNDIHQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DNMMSPGN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YTRACRSR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YKLKSQHN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CIQWHLST.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YCEMFQTY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NPCKFEER.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CPLSWKIC.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-LLYCHPVC.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QTNSMWVW.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GINLHEPA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MNNTAFAR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-AKMNGAKS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-EIWHQCVV.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HNNNNYPI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RQLKCGWI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YFPLWFTA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WLSHFPYK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QFPLQPCE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FNMNYVPM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YPQQQDWD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HWTFRTRL.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-TYSGQGWY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WNHVFLNP.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WCPYTEGA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PLIFNRKQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-ALMCLIKY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HDDCTQYT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-TPICCYRA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-ESRYWMKS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YNGWAISL.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VKPPKPFS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CDGDANYN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WQKMTTIP.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-LLGMTHKH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PEQVTVCP.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PWVNPNCW.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RTCFCLWI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-LTYYPSMY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CLPKLHLY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-LHVYHTLQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DNFYYHPD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RCDCGFHI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NPVIPHTN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GWVSPLFV.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-KGPEQHNT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YQHNACRH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-ACCASYIS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WQCYWSCD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-LCHIQYSY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-EWMRSSWE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VCGYHISF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GHSVVRNT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-SCLQLKRP.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YDNEFKSY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-KMDVMIKN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-AKIEAEVQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-LDDGQWLQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PTPTEDAD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DFMDTDVM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MWIGWIPE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-EWSFSEYE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NTNKRRNI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DAWHWIRE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DYKIVIYH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NWGEIYNF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RNICMKCD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NMVWYITN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-TVQYMKPC.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WMKPKIYN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-EDDCPLCA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-SRPEVCCS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FPWCCPSR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HIERARWQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PQKNGCKQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HTSDRSAF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DKSHTVEY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HHPCECSS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HMPRLAMD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-EAYHQNST.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-AEQVDEGP.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-SEQQFIGM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-AYVGMQYQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NCYNGTMA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-SPYHQVND.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CWIQRCSQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-KCDSNDIE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GESSEVET.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FKRCPLAS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VMFRCYMK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WSKSHTET.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RIVPLYQM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YYLFADEI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-EMEKKPMD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-AYFEWGEN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-TRCDTLIF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NMQMTFFL.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MILDQLMY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-TALAQSVM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-IVWYGHPW.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GDHGGERG.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MLESTKGY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-ACAMSPSR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YCNEWPSR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MAPMDTPG.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YILKSMQP.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NKHMMDVQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-SKTVSHSK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WVRVQWCH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-LLIVHHGE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-INSGVMMG.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GQKRIRVP.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CVEAQQTG.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PLNYAQDS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-ELDLGDLT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-IHEKRVKV.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-ISFCTSCA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-LNDTYHDK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QCYVNRFT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-EEGMPKMM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CCHSIERL.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FQNFLNQM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RWLDRSCF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PGRGMDCW.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CCRARNWK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-ERWSHSQF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-KHITPKCS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FSYIVKGE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-WCAAWAHQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YHPIRMDE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HSWNVKYM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FREWFTGS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MALDYAGQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VPGTYHCQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RTGLVYDV.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QCCYYVKN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QQWVDNQL.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-KFNHKDIT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QSYDICSC.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QRKVIASD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QQRWKGEQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VDLCLMYQ.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PDLFTQEK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FYADRYHR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-NQAAEEEI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RIDIFEWC.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-KNNYNDWH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-RPDVDVHH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FPTIGGCI.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-PNDSYFMF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-SYNCPGYR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-TNNRQQQM.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YQVMGWWD.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-QKPKSFYH.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-YGEMKKGT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MKRMREIR.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-TPYMDVLN.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-EIAKHQAT.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-KGTQCVYF.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VMYMQRDW.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-VWQCAPWC.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-DMWSNTHG.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-MTRWNHDY.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-FWDVPAFG.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GTNFRHAS.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-TFSVPLTK.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-GHKTMYGA.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CIMFYFFL.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-IIHCMHRE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-CCGHSKGE.tif',
  '/home/ravi/Domain_adap_code/fhist_dataset/NCT_Target/Data_target_folder/Benign/NORM-HWPTQFHV.tif',

In [9]:
df = pd.DataFrame(data_record)

In [10]:
df.head()

,path,slide_name,label
0,/home/ravi/Domain_adap_code/fhist_dataset/NCT_...,NORM-GGYHFAVK.tif,Benign
1,/home/ravi/Domain_adap_code/fhist_dataset/NCT_...,NORM-ECPVWKSG.tif,Benign
2,/home/ravi/Domain_adap_code/fhist_dataset/NCT_...,NORM-VDCVCPSP.tif,Benign
3,/home/ravi/Domain_adap_code/fhist_dataset/NCT_...,NORM-PEPNIHAQ.tif,Benign
4,/home/ravi/Domain_adap_code/fhist_dataset/NCT_...,NORM-IANDFGMH.tif,Benign

In [11]:
df.label[df.label=='Benign']=0
df.label[df.label=='Stroma']=1
df.label[df.label=='Tumor']=2
df.label[df.label=='Debris']=3
df.label[df.label=='Inflammatory']=4
df.label[df.label=='Muscle']=5

In [12]:
df.head()

                                                path         slide_name label
0  /home/ravi/Domain_adap_code/fhist_dataset/NCT_...  NORM-GGYHFAVK.tif     0
1  /home/ravi/Domain_adap_code/fhist_dataset/NCT_...  NORM-ECPVWKSG.tif     0
2  /home/ravi/Domain_adap_code/fhist_dataset/NCT_...  NORM-VDCVCPSP.tif     0
3  /home/ravi/Domain_adap_code/fhist_dataset/NCT_...  NORM-PEPNIHAQ.tif     0
4  /home/ravi/Domain_adap_code/fhist_dataset/NCT_...  NORM-IANDFGMH.tif     0

In [13]:

#df = pd.DataFrame(data_record)
df.to_csv('data_target_test.csv',index=False)